# -*- coding: utf-8 -*-
"""TwilioSms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MIcTavosGt0PJO1zM8FZdBZqAQrIh0LZ
"""

import json 
from getpass import getpass

reset_creds = False

if reset_creds:
  twilio_sid = getpass('Whats the twilio SID')
  twilio_secret = getpass('Whats your twilio secret pass')

  data = {
      "twilio_sid" : twilio_sid,
      "twilio_secret" : twilio_secret
  }

  json_data = json.dumps(data)

  with open('creds.json','w') as fil:
    fil.write(json_data)

#!pip install twilio

!cat creds.json

#!pip install twilio

twilio_sid = 'AC20922e98d487284f06fdf0956cc1ee30'
twilio_secret = '5dc69c7bdaa4c0fbda1e341d1ab6f30a'

'''
with open('creds.json','r') as fil:
  orig_data = fil.read()
  credent_data = json.loads(orig_data)
  twilio_sid = credent_data.get(twilio_sid)
  twilio_secret = credent_data.get(twilio_secret)
'''

first_number = '+12678713632'

second_number = '+919842962727'

from twilio.rest import Client

client = Client(twilio_sid,twilio_secret)

body = "Hello World"
message_twilio = client.messages.create(
    body = body,
    from_ = first_number,
    to = second_number
)